Suggested edit to avoid text buffer exception
Some files were giving me errors with Perl 5.22.0... it's probably an underlying problem that can be fixed better than this, but this is the quick fix I employed to your coffee script to avoid the error.

The error I was getting is:

```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432:29)
    at /Users/sterling/.atom/packages/linter-perl-check-syntax/lib/linter-perl-check-syntax.coffee:54:59
    at process._tickCallback (node.js:368:9)
```

The output from perl that was causing the error is this (with corporate secret bits elided):

```
Can't locate DateTime/Format/Natural.pm in @INC (you may need to install the DateTime::Format::Natural module) (@INC contains: lib /home/dir/.plenv/versions/5.22.0/lib/perl5/site_perl/5.22.0/darwin-2level /home/dir/.plenv/versions/5.22.0/lib/perl5/site_perl/5.22.0 /home/dir/.plenv/versions/5.22.0/lib/perl5/5.22.0/darwin-2level /home/dir/.plenv/versions/5.22.0/lib/perl5/5.22.0 .) at lib/XXX.pm line 61.
BEGIN failed--compilation aborted at lib/XXX.pm line 61.
Compilation failed in require at lib/XXY.pm line 0.
Compilation failed in require at lib/XXZ.pm line 22.
BEGIN failed--compilation aborted at lib/XXZ.pm line 22.
```

I suspect it's that "line 0" bit that's the real problem.